version: "0.0.3"
verbose: false
# Options for log level are INFO, DEBUG, WARNING, ERROR
log-level: ERROR

menu:
  num-of-rows: 6
  unused-marker-x: 0
  unused-marker-y: 5
  close-marker-x: 8
  close-marker-y: 5

global-multipliers:
  pvp-damage: 0.5
  combat-exp: 0.0
  skill-exp: 0.0
  item-drop: 0.0
  item-rarity: 0.0

xp-bonus: 0.0
drops-bonus: 0.0

mechanics:
  base-bleed-damage: 1
  percent-bleed-damage: 0.1
  ticks-per-bleed: 12
  health-bar-duration: 200

leveled-monsters:
  name-format: "&7%ENTITY% &f(%LEVEL%)"
  give-skeletons-sword-chance: 0.1
  give-skeletons-wand-chance: 0.1
  replace-witch-evoker: 0.15
  replace-witch-illusioner: 0.05
  killer-bunny-chance: 0.05
  mob-rankup-chance: 0.1
  enabled-worlds:
    world:
      starting-level: 3
      distance-per-level: 150
    hard-world:
      starting-level: 50
      distance-per-level: 100

## NOTE: XP penalty exempt world applies to the world the
## player RESPAWNS in, as that is when xp is lost!
penalty-free-worlds:
- WeenieWorld

leveling:
  max-skill-level: 60
  formula: (5+(2*LEVEL)+(LEVEL^1.2))*LEVEL
  crafting: 50 + (LEVEL * 25) + (LEVEL^3)
  fishing: 50 + (LEVEL * 25) + (LEVEL^3)
  enchanting: 50 + (LEVEL * 25) + (LEVEL^3)

language:
  skill-up-self: "{c}&lSkill Up! {c}Your skill level in &f{n} {c}has increased to &f{l}{c}!"
  skill-up-broadcast: "{c}&lSkill Up! &f{p} {c}has reached &f{n} {c}skill level &f{l}{c}!"
  bar-title-entity-killed:
  - '&c&lENEMY SLAIN!'
  - 'ded'

configuration-load-period: 10