version: "0.0.3"
verbose: false
# Options for log level are INFO, DEBUG, WARNING, ERROR
log-level: ERROR

menu:
  num-of-rows: 6
  unused-marker-x: 0
  unused-marker-y: 5
  close-marker-x: 8
  close-marker-y: 5

ability-menus:
  BASIC_LEVEL_MENU:
    - "instant-ignite"
  MELEE_ABILITY:
     - "instant-ignite"
  MAGIC_ABILITY:
    - "instant-ignite"
  ARCHERY_ABILITY:
    - "instant-ignite"
  LIFE_SKILL:
    - "instant-ignite"

mechanics:
  pvp-damage: 0.5
  evasion-threshold: 0.5
  sneak:
    sneak-skill-effectiveness: 80
    detection-threshold: 10000
    base-detection-when-unseen: 500
    base-detection-when-seen: 1500
    per-lvl-detection-when-unseen: 30
    per-lvl-detection-when-seen: 80
    maximum-head-angle-for-seen: 0.3
    maximum-sneak-exp-range-squared: 144
  base-bleed-damage: 1
  percent-bleed-damage: 0.1
  ticks-per-bleed: 12
  health-bar-duration: 200
  skill-bar-duration: 200

custom-spawn-limits:
  world:
    base-spawn-limit: 200
    per-player-spawn-limit: 10
  hard-world:
    base-spawn-limit: 1000
    per-player-spawn-limit: 100

leveled-monsters:
  name-format: "&7%ENTITY% &f(%LEVEL%)"
  add-mod-chance: 0.2
  max-mob-mods: 3
  give-skeletons-sword-chance: 0.1
  give-skeletons-wand-chance: 0.1
  replace-witch-evoker: 0.15
  replace-witch-illusioner: 0.05
  killer-bunny-chance: 0.05
  mob-rankup-chance: 0.1
  enabled-worlds:
    world:
      starting-level: 3
      distance-per-level: 150
    hard-world:
      starting-level: 50
      distance-per-level: 100

## NOTE: XP penalty exempt world applies to the world the
## player RESPAWNS in, as that is when xp is lost!
penalty-free-worlds:
- WeenieWorld

leveling:
  max-skill-level: 60
  formula: (5+(2*LEVEL)+(LEVEL^1.2))*LEVEL
  crafting: 50 + (LEVEL * 25) + (LEVEL^3)
  fishing: 50 + (LEVEL * 25) + (LEVEL^3)
  enchanting: 50 + (LEVEL * 25) + (LEVEL^3)

configuration-load-period: 10