name: Strife
version: ${project.version}
main: info.faceland.strife.StrifePlugin
depend: [Facecore, Beast]
softdepend: [Loot, Bullion]

commands:
  stats:
    aliases: [st]
  levelup:
    aliases: [lu]
  strife:
    aliases: [str]

permissions:
  strife.command.stats:
    default: true
  strife.command.levelup:
    default: true
  strife.command.strife.reset:
    default: op
  strife.command.strife.clear:
    default: op
  strife.command.strife.raise:
    default: op
  strife.command.strife.addxp:
    default: op
  strife.xp:
    default: false
  strife.mult.75:
    default: false
  strife.mult.125:
    default: false
  strife.mult.150:
    default: false
  strife.mult.175:
    default: false
  strife.mult.200:
    default: false