name: ${project.build.name}
version: ${project.build.version}
main: info.faceland.strife.StrifePlugin
depend: [Facecore]

commands:
  stats:
    aliases: [st]
  levelup:
    aliases: [lu]

permissions:
  strife.command.stats:
    default: true
  strife.command.levelup:
    default: true