name: Strife
version: ${project.version}
main: info.faceland.strife.StrifePlugin
api-version: 1.14
depend: [Facecore, ProtocolLib]
softdepend: [Loot, Bullion]

commands:
  stats:
    aliases: [st]
  inspect:
    aliases: [look]
  levelup:
    aliases: [lu]
  strife:
    aliases: [str]
  spawner:
    aliases: [spn]

permissions:
  strife.command.stats:
    default: true
  strife.command.levelup:
    default: true
  strife.command.strife.reset:
    default: op
  strife.command.strife.clear:
    default: op
  strife.command.strife.raise:
    default: op
  strife.command.strife.addxp:
    default: op
  strife.command.spawner:
    default: op
  strife.command.reload:
    default: op
  strife.xp:
    default: false
  strife.mult.75:
    default: false
  strife.mult.125:
    default: false
  strife.mult.150:
    default: false
  strife.mult.175:
    default: false
  strife.mult.200:
    default: false