name: Strife
version: ${project.version}
main: land.face.strife.StrifePlugin
api-version: 1.15
depend: [Facecore, ProtocolLib]
softdepend: [Loot, Bullion, LibsDisguises, SnazzyParties]

commands:
  cast:
    aliases: [ability-macro]
  stats:
    aliases: [st]
  inspect:
    aliases: [look]
  levelup:
    aliases: [lu]
  strife:
    aliases: [str]
  spawner:
    aliases: [spn]
  agility:
    aliases: [agi]

permissions:
  strife.command.stats:
    default: true
  strife.command.cast:
    default: true
  strife.command.levelup:
    default: true
  strife.command.strife.reset:
    default: op
  strife.command.strife.clear:
    default: op
  strife.command.strife.raise:
    default: op
  strife.command.strife.addxp:
    default: op
  strife.command.spawner:
    default: op
  strife.command.reload:
    default: op
  strife.xp:
    default: false